#!/command/with-contenv sh
# Prismarr — initialization script, runs ONCE at container startup, before
# frankenphp and messenger-worker (s6 oneshot dependency).
#
# Responsibilities:
#   1. Ensure the var/data directory (volume mount) is writable.
#   2. Generate a .env.local with random secrets on first boot, persisted
#      in the volume so it survives image rebuilds.
#   3. Create the SQLite schema if the database is empty.
#
# Idempotent: safe to run on every boot, only acts when needed.

set -e

APP_DIR="/var/www/html"
DATA_DIR="$APP_DIR/var/data"
ENV_STORED="$DATA_DIR/.env.local"
ENV_LINK="$APP_DIR/.env.local"
DB_FILE="$DATA_DIR/prismarr.db"

PRISMARR_VERSION="${PRISMARR_VERSION:-1.0.0-dev}"
PRISMARR_PORT="${PRISMARR_PORT:-7070}"
APP_ENV="${APP_ENV:-prod}"

# Status flags (populated during the run, printed in the summary)
secrets_action="already configured"
schema_action="already up to date"

# ── 1. Writable volume ──────────────────────────────────────────────────────
mkdir -p "$DATA_DIR" "$APP_DIR/var/cache" "$APP_DIR/var/log" "$APP_DIR/var/sessions"
chown -R www-data:www-data "$APP_DIR/var"

# ── 2. Secrets generation on first boot ─────────────────────────────────────
if [ ! -f "$ENV_STORED" ]; then
  APP_SECRET=$(openssl rand -hex 32)
  MERCURE_JWT_SECRET=$(openssl rand -hex 32)
  JWT_PASSPHRASE=$(openssl rand -hex 32)

  cat > "$ENV_STORED" <<EOF
# Secrets auto-generated by Prismarr's init script on first boot.
# Persisted in the prismarr_data volume. Do not commit, do not edit manually
# unless you want to rotate them.

APP_SECRET=$APP_SECRET
MERCURE_JWT_SECRET=$MERCURE_JWT_SECRET
JWT_PASSPHRASE=$JWT_PASSPHRASE
EOF

  chown www-data:www-data "$ENV_STORED"
  chmod 600 "$ENV_STORED"
  secrets_action="generated"
fi

# Symlink .env.local → volume if nothing exists at the project root
# (dev bind-mount may already provide a real file, respect it).
if [ ! -e "$ENV_LINK" ]; then
  ln -s "$ENV_STORED" "$ENV_LINK"
fi

# ── 3. Database schema on first boot ────────────────────────────────────────
if [ ! -f "$DB_FILE" ] || [ ! -s "$DB_FILE" ]; then
  cd "$APP_DIR"
  php bin/console doctrine:schema:create --no-interaction >/dev/null 2>&1 || \
    php bin/console doctrine:schema:update --force --no-interaction >/dev/null 2>&1
  chown www-data:www-data "$DB_FILE" 2>/dev/null || true
  schema_action="created"
fi

# ── Startup banner ──────────────────────────────────────────────────────────
cat <<BANNER

╭──────────────────────────────────────────────────────────────╮
│                                                              │
│      ██████╗ ██████╗ ██╗███████╗███╗   ███╗ █████╗ ██████╗   │
│      ██╔══██╗██╔══██╗██║██╔════╝████╗ ████║██╔══██╗██╔══██╗  │
│      ██████╔╝██████╔╝██║███████╗██╔████╔██║███████║██████╔╝  │
│      ██╔═══╝ ██╔══██╗██║╚════██║██║╚██╔╝██║██╔══██║██╔══██╗  │
│      ██║     ██║  ██║██║███████║██║ ╚═╝ ██║██║  ██║██║  ██║  │
│      ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝  │
│                                                              │
│              Self-hosted media stack dashboard               │
│                                                              │
╰──────────────────────────────────────────────────────────────╯

  Version        : $PRISMARR_VERSION
  Environment    : $APP_ENV
  Listening on   : http://0.0.0.0:$PRISMARR_PORT
  Database       : $DB_FILE
  Secrets file   : $ENV_STORED

  Boot checks
  ──────────────────────────────────────────────────────────
  [ok] Secrets                $secrets_action
  [ok] Database schema        $schema_action

  Ready — open http://localhost:$PRISMARR_PORT to access the UI.
  If this is a first install, you will be redirected to the
  setup wizard to create your admin account and configure
  your services (Radarr, Sonarr, qBittorrent, ...).

BANNER
